### ISSUE TITLE
artifact-deployment bach job fails to complete 

### ISSUE THREAD

**Issue by AllaeddineEL** [OpenUnison/openunison-k8s-login-oidc#10]
following deployment step in docs, artifact-deployment bach job fails to complete with the following output 
```console 
namespace/openunison-deploy created
configmap/extracerts created
secret/input created
configmap/deployment-scripts created
clusterrolebinding.rbac.authorization.k8s.io/artifact-deployment created
job.batch/artifact-deployment created
NAME                        READY   STATUS              RESTARTS   AGE
artifact-deployment-97fpw   0/1     ContainerCreating   0          0s
artifact-deployment-97fpw   1/1   Running   0     1s
artifact-deployment-97fpw   0/1   Error   0     3s
artifact-deployment-5zh4g   0/1   Pending   0     0s
artifact-deployment-5zh4g   0/1   Pending   0     0s
artifact-deployment-5zh4g   0/1   ContainerCreating   0     0s
artifact-deployment-5zh4g   1/1   Running   0     2s
artifact-deployment-5zh4g   0/1   Error   0     8s
```
the logs from one job pods are showing:
```console 
$ kubectl logs -f artifact-deployment-97fpw -nopenunison-deploy                                                                                                                                                                                    Processing - '/etc/extracerts/..2019_08_19_14_15_46.852569665'                                                                                                                                                                                     not a pem, sipping
Processing - '/etc/extracerts/..data'
not a pem, sipping
Processing - '/etc/extracerts/ca-devops.pem'
Processing - '/etc/extracerts/input.props'
not a pem, sipping
Processing - '/etc/extracerts/..2019_08_19_14_15_46.852569665'
not a pem, sipping
Processing - '/etc/extracerts/..data'
not a pem, sipping
Processing - '/etc/extracerts/ca-devops.pem'
Processing - '/etc/extracerts/input.props'
not a pem, sipping
Loading CertUtils
Creating openunison keystore
Exception in thread "main" javax.script.ScriptException: TypeError: null has no such function "toCharArray" in <eval> at line number 30
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:119)
Caused by: <eval>:30 TypeError: null has no such function "toCharArray"
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:180)
        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:66)
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
        at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:30)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        ... 5 more
```

**Comment by mlbiam** [comment]
Check the `unisonKeystorePassword` in your `secrets/input.props`.  Looks like its missing

**Comment by AllaeddineEL** [comment]
the secret was there, but vscode has removed the line brakes from the property files which resulted  that error
